import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { StoreProvider } from "./context/StoreContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Backend Tutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full bg-slate-900 text-slate-100">
        {/* 1. Sidebar Container */}
        <StoreProvider>
          <aside className="w-64 border-r dark:bg-black bg-white border-slate-800 p-4 shrink-0">
            <Sidebar />
          </aside>

          {/* 2. Main Content Container */}
          <main className="flex-1 flex flex-col dark:bg-slate-800 bg-dark/10  min-w-0 overflow-y-auto h-lhv">
            {children}
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
